allprojects {
    group = "me.kiriyaga"
    version = "v1.1.1"

    repositories {
        mavenCentral()
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://repo.spongepowered.org/maven") }
        maven {
            url = uri("https://api.modrinth.com/maven")
            content {
                includeGroup("maven.modrinth")
            }
        }
        maven { url = uri("https://jitpack.io") }
    }
}

tasks.register("runClient") {
    dependsOn(":client:runClient")
}

subprojects {
    apply plugin: 'java'
}
