plugins {
    id 'fabric-loom' version '1.15.3'
    id 'maven-publish'
    id 'java'

}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://repo.spongepowered.org/maven" }

    mavenCentral()
}

loom {
    accessWidenerPath = file("src/main/resources/META-INF/nami.accesswidener")

    mods {
        "nami-api" {
            sourceSet project(":nami-api").sourceSets.main
        }
        "nami-client" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                loader_version: project.loader_version,
                minecraft_version: project.minecraft_version
        )
    }
}

group = project.maven_group
version = project.mod_version

tasks.register("printVersion") {
    doLast {
        println project.mod_version
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    include implementation(project(path: ":nami-api", configuration: "namedElements"))
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
