plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    maven {
        url = uri("https://maven.pkg.github.com/NamiDevelopment/nami")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
    }

    maven { url = "https://maven.fabricmc.net/" }

    maven { url = "https://repo.spongepowered.org/maven" }

    maven { url = "https://jitpack.io" }

    mavenCentral()

}
loom {
    accessWidenerPath = file("src/main/resources/META-INF/nami.accesswidener")
}

group = "namidevelopment.kiriyaga"

processResources {
    inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                loader_version: project.loader_version,
                minecraft_version: project.minecraft_version
        )
    }
}
version = project.mod_version

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"


    dependencies {
        modCompileOnly "namidevelopment.kiriyaga:nami-api:1.1.1"
    }

    modImplementation("com.github.cattyngmd.catformat:catformat-core:2.1.0")
    include("com.github.cattyngmd.catformat:catformat-core:2.1.0")
}
