plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://repo.spongepowered.org/maven" }
    maven {
        url = "https://api.modrinth.com/maven"
        content { includeGroup("maven.modrinth") }
    }
    maven { url = "https://jitpack.io" }
}

processResources {
    inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand(
                version: project.version,
                loader_version: project.loader_version,
                minecraft_version: project.minecraft_version
        )
    }
}

group = project.maven_group
version = project.mod_version

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation("com.github.cattyngmd.catformat:catformat-core:2.1.0")
    include("com.github.cattyngmd.catformat:catformat-core:2.1.0")
}