permissions:
  contents: write

name: build upload release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' ##Each monday

jobs:
  build:
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.ref_name }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: chmod Gradlew
        run: chmod +x ./gradlew

      - name: Build client
        run: ./gradlew clean build remapJar --stacktrace

      - name: Set branch name
        run: |
          SAFE_BRANCH="${{ github.ref_name }}"
          SAFE_BRANCH="${SAFE_BRANCH//./-}"
          echo "SAFE_BRANCH=$SAFE_BRANCH" >> $GITHUB_ENV

      - name: Set version from JAR
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" | head -n 1)
          VERSION=$(unzip -p "$JAR_PATH" fabric.mod.json | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" > version.txt

      - name: Upload build JAR
        uses: actions/upload-artifact@v4
        with:
          name: nami-${{ env.SAFE_BRANCH }}
          path: |
            build/libs/*.jar
            version.txt

  release:
    needs: build
    if: github.actor == 'Kiriyaga7615'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifact

      - name: Read version
        run: |
          VERSION=$(cat ./artifact/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          git fetch --prune --unshallow || true
          COMMITS=$(git log --pretty=format:"- %s by %an" origin/main..HEAD)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Nami ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Upload all artifacts
        run: |
          shopt -s nullglob
          JAR_FILES=(./artifact/*/*.jar)
          if [ ${#JAR_FILES[@]} -eq 0 ]; then
            echo "No JAR files found, exiting"
            exit 1
          fi
          for file in "${JAR_FILES[@]}"; do
            echo "Uploading $file to release tag ${{ env.VERSION }}"
            gh release upload ${{ env.VERSION }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
