name: client_build_upload_artifact

on:
  workflow_dispatch:
  push:
  pull_request:


permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Permissions
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew :nami-client:build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nami-client
          path: nami-client/build/libs/*.jar
